// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactProjectAPI.Infrastructure.Data;

#nullable disable

namespace ReactProjectAPI.Infrastructure.Migrations
{
    [DbContext(typeof(ReactProjectAPIContext))]
    [Migration("20251105061804_finalmigration")]
    partial class finalmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReactProjectAPI.Domain.Entities.Approval", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalId"));

                    b.Property<DateTime>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApprovalId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("ClaimId")
                        .IsUnique();

                    b.ToTable("Approvals");

                    b.HasData(
                        new
                        {
                            ApprovalId = 1,
                            ApprovalDate = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApprovedBy = 2,
                            ClaimId = 1,
                            Comments = "Valid expense, approved.",
                            Status = "Approved"
                        },
                        new
                        {
                            ApprovalId = 2,
                            ApprovalDate = new DateTime(2024, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApprovedBy = 2,
                            ClaimId = 2,
                            Comments = "Bill not clear, rejected.",
                            Status = "Rejected"
                        });
                });

            modelBuilder.Entity("ReactProjectAPI.Domain.Entities.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiptImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ClaimId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            ClaimId = 1,
                            Amount = 4500m,
                            CategoryId = 1,
                            Description = "Travel expenses for client meeting at Hyderabad.",
                            ExpenseDate = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiptImage = "receipts/travel1.jpg",
                            Status = "Approved",
                            SubmittedDate = new DateTime(2024, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Client Visit Travel",
                            UserId = 3
                        },
                        new
                        {
                            ClaimId = 2,
                            Amount = 1800m,
                            CategoryId = 2,
                            Description = "Lunch with team after project delivery.",
                            ExpenseDate = new DateTime(2024, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiptImage = "receipts/food1.jpg",
                            Status = "Rejected",
                            SubmittedDate = new DateTime(2024, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Team Lunch",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("ReactProjectAPI.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "IT",
                            Description = "Information Technology"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Finance",
                            Description = "Finance Department"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "HR",
                            Description = "Human Resources"
                        });
                });

            modelBuilder.Entity("ReactProjectAPI.Domain.Entities.ExpenseCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("ExpenseCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Travel",
                            Description = "Travel related expenses"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Meals",
                            Description = "Food and dining expenses"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Office Supplies",
                            Description = "Office equipment and supplies"
                        });
                });

            modelBuilder.Entity("ReactProjectAPI.Domain.Entities.Reimbursement", b =>
                {
                    b.Property<int>("ReimbursementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReimbursementId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReimbursementId");

                    b.HasIndex("ClaimId")
                        .IsUnique();

                    b.HasIndex("ProcessedBy");

                    b.ToTable("Reimbursements");

                    b.HasData(
                        new
                        {
                            ReimbursementId = 1,
                            Amount = 1800m,
                            ClaimId = 2,
                            PaymentDate = new DateTime(2024, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Bank Transfer",
                            ProcessedBy = 1,
                            Status = "Paid",
                            TransactionReference = "TXN001"
                        },
                        new
                        {
                            ReimbursementId = 2,
                            Amount = 4500m,
                            ClaimId = 1,
                            PaymentDate = new DateTime(2024, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Bank Transfer",
                            ProcessedBy = 1,
                            Status = "Paid",
                            TransactionReference = "TXN002"
                        });
                });

            modelBuilder.Entity("ReactProjectAPI.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "finance@gmail.com",
                            Name = "Jagadish",
                            Password = "Finance123",
                            Role = 3
                        },
                        new
                        {
                            UserId = 2,
                            CreatedDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "manager@gmail.com",
                            Name = "Gokul",
                            Password = "Manager123",
                            Role = 2
                        },
                        new
                        {
                            UserId = 3,
                            CreatedDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "employee@gmail.com",
                            Name = "Lavan",
                            Password = "Employee123",
                            Role = 1
                        });
                });

            modelBuilder.Entity("ReactProjectAPI.Domain.Entities.Approval", b =>
                {
                    b.HasOne("ReactProjectAPI.Domain.Entities.User", "ApprovedByUser")
                        .WithMany("Approvals")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReactProjectAPI.Domain.Entities.Claim", "Claim")
                        .WithOne("Approval")
                        .HasForeignKey("ReactProjectAPI.Domain.Entities.Approval", "ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ReactProjectAPI.Domain.Entities.Claim", b =>
                {
                    b.HasOne("ReactProjectAPI.Domain.Entities.ExpenseCategory", "Category")
                        .WithMany("Claims")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReactProjectAPI.Domain.Entities.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReactProjectAPI.Domain.Entities.Reimbursement", b =>
                {
                    b.HasOne("ReactProjectAPI.Domain.Entities.Claim", "Claim")
                        .WithOne("Reimbursement")
                        .HasForeignKey("ReactProjectAPI.Domain.Entities.Reimbursement", "ClaimId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReactProjectAPI.Domain.Entities.User", "ProcessedByUser")
                        .WithMany("Reimbursements")
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("ProcessedByUser");
                });

            modelBuilder.Entity("ReactProjectAPI.Domain.Entities.User", b =>
                {
                    b.HasOne("ReactProjectAPI.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ReactProjectAPI.Domain.Entities.Claim", b =>
                {
                    b.Navigation("Approval")
                        .IsRequired();

                    b.Navigation("Reimbursement")
                        .IsRequired();
                });

            modelBuilder.Entity("ReactProjectAPI.Domain.Entities.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ReactProjectAPI.Domain.Entities.ExpenseCategory", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("ReactProjectAPI.Domain.Entities.User", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Claims");

                    b.Navigation("Reimbursements");
                });
#pragma warning restore 612, 618
        }
    }
}
